### ISSUE TITLE
Error: Loading state_dict

### ISSUE THREAD

**Issue by raniasyed** [tjpulkl/CDGNet#11]
C:\Users\Rania\Documents\Human-Parsing-PyTorch>python evaluate_multi.py
Traceback (most recent call last):
  File "C:\Users\Rania\Documents\Human-Parsing-PyTorch\evaluate_multi.py", line 254, in <module>
    main()
  File "C:\Users\Rania\Documents\Human-Parsing-PyTorch\evaluate_multi.py", line 221, in main
    model.load_state_dict(state_dict)
  File "C:\Users\Rania\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\torch\nn\modules\module.py", line 2189, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ResNet:

I am unable to resolve this error since the new version of the LIP model with all the weights is not available now. Please help me out.

**Comment by SharmaVibhor** [comment]
I think i am facing similar issue by not having the latest model. Did you solve this ?

**Comment by tjpulkl** [comment]
Hi, I have tested the trained model, there is no problem. Please ensure that you correctly use the trained model download from baidu which has the file name of "LIP_epoch_149.pth", not the imagenet pretrained model's file.

**Comment by tjpulkl** [comment]
Please download the trained model for LIP dataset from [baidu drive](https://pan.baidu.com/s/1WyifPOOE0SqIzCje-d1kzA?pwd=81la) and put it into snapshots folder.
